include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI CoT / multicast status for GL.iNet GL-AXT1800
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
